#!/bin/bash
# Switch kube config context
function kube-ctx-switch-current() {
	local context=$1

	if [[ $context == "" ]]; then
		context=$(kubectl config get-contexts --no-headers -o name | fzf)
	fi

	if [[ $context == "" ]]; then
		echo "no context provided." 2>&1
		return 1
	fi

	kubectl config use-context "$context"
}
