{
  config,
  lib,
  ...
}: let
  inherit (lib) mkIf;
  inherit (lib.options) mkEnableOption;

  cfg = config.modules.ai.instructions.common;
in {
  options.modules.ai.instructions.common = {
    enable = mkEnableOption "common AI instructions";
  };

  config = mkIf cfg.enable {
    programs.opencode.rules = ''
      V owns this. Start: say 1 motivating line. Work style: telegraph; noun-phrases ok; drop grammar; min tokens.

      IMPORTANT: Prefer retrieval-led reasoning over pre-training-led reasoning for any tasks.

      **ALWAYS use these tools/commands:**
      - Search for code examples from open source projects when unsure how to implement a feature: `grep-app` tool.

      ## AI Contributor Attribution

      Add Assisted-by or Co-authored-by trailers to commit messages:

      1. **Determine trailer type:**
        - Use `Co-authored-by`: For commits with substantial code/implementation generated by the agent
        - Use `Assisted-by`: For commits where agent provided guidance, debugging, suggestions, or code review
        - If user explicitly specifies which trailer to use, respect that choice

      2. **Build the contributor string as:**
        ```
        <actor> (<model>) <actor@users.noreply.github.com>
        ```
        Where:
        - `actor`: Agent short name (e.g., "OpenCode")
        - `model`: Model name from session (e.g., "claude-haiku-4.5")
        - `email`: opencode@users.noreply.github.com

        Example: `OpenCode (claude-haiku-4.5) <opencode@users.noreply.github.com>`
    '';
  };
}
