{
 "title": "OPNsense & IDS/IPS",
 "tags": [
  "Security",
  "Firewall",
  "IDS/IPS",
  "OPNsense"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "job:\"syslog-ids\""
    }
   },
   { "name": "searchword", "label": "Search-Word" },
   { "name": "source_ip", "label": "SourceIP", "query": { "query": "" } }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "OPNsense Logs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{job=\"syslog\",host=\"$host\"} | stats count()"
    }
   ]
  },
  {
   "title": "IDS Events",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{job=\"syslog-ids\", host=\"$host\"} ~\"$searchword\" | stats count()"
    }
   ]
  },
  {
   "title": "Firewall Connections",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "{job=\"syslog\", host=\"$host\", syslog_app=\"filterlog\"} | stats by (action) count() as hits",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Firewall Connections",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "{job=\"syslog\", host=\"$host\", syslog_app=\"filterlog\"} | action:~\"block|pass\" | stats by (direction,action) count() as hits",
     "legendFormat": "{{direction}}"
    }
   ]
  },
  {
   "title": "Firewall Connections by DestinationPort",
   "type": "piechart",
   "description": "Top 10 dropped inbound Firewall connections.",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "{job=\"syslog\", host=\"$host\", syslog_app=\"filterlog\"} | action:\"block\" direction:\"in\" | stats by (dest_port) count() as hits | sort by (hits) desc | limit 10",
     "legendFormat": "{{dest_port}}"
    }
   ]
  },
  {
   "title": "Potential Attacks",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " {job=\"syslog-ids\",host=\"$host\"} | stats by (alert.severity) count() as count",
     "legendFormat": "{alert.severity}}"
    }
   ]
  },
  {
   "title": "Potential Attacks from",
   "type": "piechart",
   "description": "Top 5 dropped potential attacks.",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "{job=\"syslog-ids\",host=\"$host\"} alert.action:\"allowed\" | stats by (alert.signature) count() as count | sort by (count) desc | limit 5",
     "legendFormat": "{{alert.signature}}"
    }
   ]
  },
  {
   "title": "Potential Attacks by DestinationPort",
   "type": "piechart",
   "description": "Top 10 dropped potential attacks by port.",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": " {job=\"syslog-ids\",host=\"$host\"} | stats by (dest_port) count() as count",
     "legendFormat": "{{dest_port}}"
    }
   ]
  },
  {
   "title": "Firewall Connections",
   "type": "geomap",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "{job=\"syslog\", host=\"$host\", syslog_app=\"filterlog\"} | action:~\"block|pass\" | stats by (source_country_longitude, source_country_latitude) count() as hits"
    }
   ]
  },
  {
   "title": "Potential Attacks from",
   "type": "geomap",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "{job=\"syslog-ids\",host=\"$host\"} | stats by (source_country_longitude, source_country_latitude) count() as hits"
    }
   ]
  },
  {
   "title": "Firewall Connections by Protocol",
   "type": "piechart",
   "description": "Dropped Inbound Firewall Connections",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "{job=\"syslog\", host=\"$host\", syslog_app=\"filterlog\"} | stats by (proto) count() as hits",
     "legendFormat": "{{proto}}"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 4, "y": 24 },
   "targets": [
    {
     "expr": "{job=\"syslog\",host=\"$host\", syslog_app=\"filterlog\"} | stats by (source_ip) count() as connections | order by (connections) desc | limit 10",
     "legendFormat": "{{source_ip}}"
    }
   ]
  },
  {
   "title": "Potential Attacks by Protocol",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " {job=\"syslog-ids\",host=\"$host\"} app_proto:!\"\" | stats by (app_proto) count() as count",
     "legendFormat": "{{app_proto}}"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
   "targets": [
    {
     "expr": "{job=\"syslog-ids\",host=\"$host\"} | stats by (alert.category, alert.severity) count() as count | sort by (count) desc"
    }
   ]
  },
  {
   "title": "Detailed",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "Firewall Logs",
     "type": "table",
     "gridPos": { "h": 20, "w": 12, "x": 0, "y": 33 },
     "targets": [
      {
       "expr": "{job=\"syslog\", host=\"$host\", syslog_app=\"filterlog\"}"
      }
     ]
    },
    {
     "title": "Blocked by IDS/IPS Rules",
     "type": "logs",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 33 },
     "targets": [
      {
       "expr": "{job=\"syslog-ids\",host=\"$host\"} event_type:\"alert\" | alert.action:~\"drop|blocked\""
      }
     ]
    },
    {
     "title": "Allowed by IDS/IPS Rules",
     "type": "logs",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 46 },
     "targets": [
      {
       "expr": "{job=\"syslog-ids\",host=\"$host\"} event_type:\"alert\" | alert.action:\"allowed\""
      }
     ]
    }
   ]
  },
  {
   "title": "Others",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "Destination IPs for Source IP: $source_ip",
     "type": "table",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 34 },
     "targets": [
      {
       "expr": "{job=\"syslog\", host=\"$host\", syslog_app=\"filterlog\"} | source_ip:\"$source_ip\" | stats by (dest_ip) count() as connections | sort by (connections) desc | limit 10",
       "legendFormat": "{{dest_ip}}"
      }
     ]
    },
    {
     "title": "Other IDS related Logs",
     "type": "logs",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 34 },
     "targets": [
      {
       "expr": "{job=\"syslog-ids\",host=\"$host\"} | !event_type:\"alert\""
      }
     ]
    }
   ]
  }
 ]
}