# yaml-language-server: $schema=https://raw.githubusercontent.com/derailed/k9s/master/internal/config/json/schemas/views.json
views:
  v1/namespaces:
    columns:
      - NAME
      - STATUS
      - AGE
      - LABELS
