#!/bin/bash
function kube-node-ssh() {
	local providerID=$(kubectl get node -o jsonpath="{.spec.providerID}" "$1")
	local provider=$(echooj | awk -F: '{ print $1; }')
	case "$provider" in
	aws) ;;
	host=$()
	gce) ;;
	*)
		echo 1>&2 "error unknown provider"
		;;
	esac
}
kube-node-ssh
