#!/bin/bash
function kube-updateconfig-aws() {
	(
		export KUBECONFIG="$HOME/.kube/config"

		while read -r profile; do
			while read -r cluster; do
				echo "profile -> $profile -> $cluster"
				alias="EKS:$cluster"

				aws eks update-kubeconfig --profile "$profile" --name "$cluster" --alias "$alias" 2>/dev/null
			done < <(aws eks list-clusters --profile "$profile" | jq '.clusters[]' -Mr)
		done < <(aws configure list-profiles | grep AWSAdministratorAccess)
	)
}
