#!/bin/bash
function kube-updateconfig-aws() {
	local cluster="$1"
	local user="$2"
	(
		export KUBECONFIG="$HOME/.kube/config"

		alias="EKS:$cluster"

		aws eks update-kubeconfig --name "$cluster" --alias "$alias" 2>/dev/null
		if [[ "$user" != "" ]]; then
			kubectl config set-context "$alias" --user="$user"
		fi
	)
}
