# yaml-language-server: $schema=https://raw.githubusercontent.com/derailed/k9s/master/internal/config/json/schemas/k9s.json
k9s:
  ui:
    skin: tokyonight
  shellPod:
    limits:
      cpu: "1"
      memory: 256Mi
    image: busybox:1.35.0
    namespace: kube-system
    tty: true
