# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot = {
    initrd.availableKernelModules = ["nvme" "xhci_pci" "ahci" "thunderbolt" "usb_storage" "usbhid" "sd_mod"];
    initrd.kernelModules = [];
    kernelModules = ["kvm-amd"];
    extraModulePackages = [];
  };

  filesystems = {
    "/" = {
      device = "/dev/disk/by-uuid/af646889-d4b5-41f5-9bca-d4236d27410b";
      fsType = "btrfs";
      options = ["subvol=root"];
    };

    "/home" = {
      device = "/dev/disk/by-uuid/af646889-d4b5-41f5-9bca-d4236d27410b";
      fsType = "btrfs";
      options = ["subvol=home"];
    };

    "/nix" = {
      device = "/dev/disk/by-uuid/af646889-d4b5-41f5-9bca-d4236d27410b";
      fsType = "btrfs";
      options = ["subvol=nix"];
    };

    "/boot" = {
      device = "/dev/disk/by-uuid/7BF9-007D";
      fsType = "vfat";
      options = ["fmask=0022" "dmask=0022"];
    };

    "/swap" = {
      device = "/dev/disk/by-uuid/af646889-d4b5-41f5-9bca-d4236d27410b";
      fsType = "btrfs";
      options = ["subvol=swap"];
    };
  };

  swapDevices = [];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp121s0u2.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
