[kubernetes]
symbol = "⛵ "
style = "bold blue"
disabled = false

[kubernetes.context_aliases]
"gke_.*_(?P<cluster>[\\w-]+)" = "GKE:$cluster"
"arn:.*:cluster/(?P<cluster>[\\w-]+)" = "EKS:$cluster"

[terraform]
format = "via [$symbol$version]($style) "

[gcloud]
disabled = true

[status]
disabled = false
map_symbol = true

[line_break]
disabled = false
