#!/bin/bash

set -euo pipefail

if [[ $# -lt 1 ]]; then
	echo >&2 "usage: , <program> [arguments]"
	exit 1
fi

cmd="$1"
shift

attr="$(nix-locate --top-level --minimal --at-root --whole-name "/bin/${cmd}")"

if [[ "$(echo "${attr}" | wc -l)" -ne 1 ]]; then
	attr="$(echo "${attr}" | fzf-tmux -p 50%,20% --border)"
fi

if [[ -z ${attr} ]]; then
	echo >&2 "no match"
	exit 1
fi

nix shell "nixpkgs#${attr%%.*}" --command "${cmd}" "$@"
