#!/bin/bash

filename="index-x86_64-$(uname | tr "[:upper:]" "[:lower:]")"
mkdir -p ~/.cache/nix-index
cd ~/.cache/nix-index || exit 1
# -N will only download a new version if there is an update.
wget -q -N "https://github.com/Mic92/nix-index-database/releases/latest/download/$filename"
ln -f "$filename" files
